// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eimxshrcmskrjkprhbes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbXhzaHJjbXNrcmprcHJoYmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTM1MDIsImV4cCI6MjA3MDQ2OTUwMn0.-5RKTMdjHc6FU135W_aXmk6NEI0FD1w4JV6UxoMBtzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});